Failures in [node-test-pull-request/63820](https://ci.nodejs.org/job/node-test-pull-request/63820/) to [node-test-pull-request/63917](https://ci.nodejs.org/job/node-test-pull-request/63917/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-12-07.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-12-07 00:10 | 1       | 16      | 18       | 6       | 59      | 17.20%     |


### Git Failure

| Reason | <code>Command "git reset --hard" returned status code 128:</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56023/](https://ci.nodejs.org/job/node-test-pull-request/63885/), [https://github.com/nodejs/node/pull/56135/](https://ci.nodejs.org/job/node-test-pull-request/63891/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/61980/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63885/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63891/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/61980/console">Example</a></summary>

```
hudson.plugins.git.GitException: Command "git reset --hard" returned status code 128:
stdout: 
stderr: fatal: Unable to create '/home/iojs/build/workspace/node/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
```
</details>

-------


### Jenkins Failure


### Build Failure

| Reason | <code>fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56079/](https://ci.nodejs.org/job/node-test-pull-request/63828/), [https://github.com/nodejs/node/pull/56120/](https://ci.nodejs.org/job/node-test-pull-request/63873/), [https://github.com/nodejs/node/pull/56001/](https://ci.nodejs.org/job/node-test-pull-request/63886/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14880/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14870/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63828/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63886/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14880/console">Example</a></summary>

```
fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository
fatal: Could not read from remote repository.
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56078/](https://ci.nodejs.org/job/node-test-pull-request/63855/), [https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63883/)) |
| Appeared | [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14875/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63855/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63883/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14875/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins11773400318815133342.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/56093/](https://ci.nodejs.org/job/node-test-pull-request/63822/), [https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63826/), [https://github.com/nodejs/node/pull/56108/](https://ci.nodejs.org/job/node-test-pull-request/63835/), [https://github.com/nodejs/node/pull/52153/](https://ci.nodejs.org/job/node-test-pull-request/63838/), [https://github.com/nodejs/node/pull/55816/](https://ci.nodejs.org/job/node-test-pull-request/63867/), [https://github.com/nodejs/node/pull/56055/](https://ci.nodejs.org/job/node-test-pull-request/63874/), [https://github.com/nodejs/node/pull/55915/](https://ci.nodejs.org/job/node-test-pull-request/63887/), [https://github.com/nodejs/node/pull/56075/](https://ci.nodejs.org/job/node-test-pull-request/63889/), [https://github.com/nodejs/node/pull/56052/](https://ci.nodejs.org/job/node-test-pull-request/63892/), [https://github.com/nodejs/node/pull/56120/](https://ci.nodejs.org/job/node-test-pull-request/63899/), [https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63916/)) |
| Appeared | [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17982/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17963/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62412/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62356/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63822/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17982/console">Example</a></summary>

```
not ok 4239 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3489.51200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-file-shared-dependency</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63831/), [https://github.com/nodejs/node/pull/55996/](https://ci.nodejs.org/job/node-test-pull-request/63866/), [https://github.com/nodejs/node/pull/56075/](https://ci.nodejs.org/job/node-test-pull-request/63881/), [https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63884/), [https://github.com/nodejs/node/pull/56023/](https://ci.nodejs.org/job/node-test-pull-request/63885/), [https://github.com/nodejs/node/pull/56133/](https://ci.nodejs.org/job/node-test-pull-request/63912/)) |
| Appeared | [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17977/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17949/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62404/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62345/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63831/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63912/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17977/console">Example</a></summary>

```
not ok 4237 parallel/test-watch-file-shared-dependency
  ---
  duration_ms: 360117.92400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ watch file with shared dependency
      ✔ should not remove shared dependencies when unfiltering an owner (2.470875ms)
    ✔ watch file with shared dependency (2.9815ms)
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-response-status-message</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56041/](https://ci.nodejs.org/job/node-test-pull-request/63849/), [https://github.com/nodejs/node/pull/56055/](https://ci.nodejs.org/job/node-test-pull-request/63854/), [https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63916/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/31572/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63849/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/31572/console">Example</a></summary>

```
not ok 416 parallel/test-http-response-status-message
  ---
  duration_ms: 411.02400
  severity: fail
  exitcode: 3221226505
  stack: |-
    client: expected status message: OK
    client: actual status message: OK
    client: expected status message: Internal Server Error
    client: actual status message: Internal Server Error
    client: expected status message: Moved Temporarily
    client: actual status message: Moved Temporarily
    client: expected status message: 
    client: actual status message: 
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56078/](https://ci.nodejs.org/job/node-test-pull-request/63856/), [https://github.com/nodejs/node/pull/56023/](https://ci.nodejs.org/job/node-test-pull-request/63885/), [https://github.com/nodejs/node/pull/56133/](https://ci.nodejs.org/job/node-test-pull-request/63908/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/47774/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/31553/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/58008/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63908/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/47774/console">Example</a></summary>

```
not ok 3403 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 120023.74600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56112/](https://ci.nodejs.org/job/node-test-pull-request/63840/), [https://github.com/nodejs/node/pull/55905/](https://ci.nodejs.org/job/node-test-pull-request/63888/), [https://github.com/nodejs/node/pull/56158/](https://ci.nodejs.org/job/node-test-pull-request/63917/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56110/console), [test-osuosl-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56084/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/47715/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63840/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63917/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56110/console">Example</a></summary>

```
not ok 3914 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360102.42800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56095/](https://ci.nodejs.org/job/node-test-pull-request/63826/), [https://github.com/nodejs/node/pull/56071/](https://ci.nodejs.org/job/node-test-pull-request/63839/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62362/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61922/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63826/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63839/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62362/console">Example</a></summary>

```
not ok 858 parallel/test-file-write-stream4
  ---
  duration_ms: 4114.12800
  severity: fail
  exitcode: 1
  stack: |-
    node:events:491
          throw er; // Unhandled 'error' event
          ^
    
    Error: ENOSPC: no space left on device, write
    Emitted 'error' event on WriteStream instance at:
        at WriteStream.onerror (node:internal/streams/readable:1026:14)
        at WriteStream.emit (node:events:513:28)
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      errno: -28,
      code: 'ENOSPC',
      syscall: 'write'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56001/](https://ci.nodejs.org/job/node-test-pull-request/63847/), [https://github.com/nodejs/node/pull/56041/](https://ci.nodejs.org/job/node-test-pull-request/63849/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/31527/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/47721/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63847/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63849/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/31527/console">Example</a></summary>

```
not ok 1024 wpt/test-timers
  ---
  duration_ms: 1157.15500
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] negative-settimeout.any.js: unreliable in Node.js; Refs: https://github.com/nodejs/node/issues/37672
    [PASS] Clear timeout with clearInterval
    [PASS] Clear interval with clearTimeout
    [PASS] Calling setInterval with no interval should be the same as if called with 0 interval
    [PASS] Calling setInterval with undefined interval should be the same as if called with 0 interval
    [PASS] negative-setinterval
    [PASS] type-long-setinterval
    [UNEXPECTED_FAILURE][UNCAUGHT] evaluation in WPTRunner.runJsTests()
    assert_unreached: Reached unreachable code
    {
      message: 'assert_unreached: Reached unreachable code',
      stack: '    at listOnTimeout (node:internal/timers:614:17)\n' +
        '    at process.processTimers (node:internal/timers:549:7)'
    }
    Command: c:\workspace\node-test-binary-windows-js-suites\node\Release\node.exe  c:\workspace\node-test-binary-windows-js...
```
</details>

-------

