Failures in [node-test-pull-request/63993](https://ci.nodejs.org/job/node-test-pull-request/63993/) to [node-test-pull-request/64079](https://ci.nodejs.org/job/node-test-pull-request/64079/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-12-18.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-12-18 00:10 | 10      | 15      | 15       | 10      | 50      | 18.75%     |


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63993/), [https://github.com/nodejs/node/pull/56224/](https://ci.nodejs.org/job/node-test-pull-request/63998/), [https://github.com/nodejs/node/pull/56222/](https://ci.nodejs.org/job/node-test-pull-request/64013/), [https://github.com/nodejs/node/pull/56228/](https://ci.nodejs.org/job/node-test-pull-request/64017/), [https://github.com/nodejs/node/pull/56239/](https://ci.nodejs.org/job/node-test-pull-request/64029/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64032/), [https://github.com/nodejs/node/pull/56106/](https://ci.nodejs.org/job/node-test-pull-request/64036/), [https://github.com/nodejs/node/pull/56060/](https://ci.nodejs.org/job/node-test-pull-request/64040/), [https://github.com/nodejs/node/pull/56213/](https://ci.nodejs.org/job/node-test-pull-request/64042/), [https://github.com/nodejs/node/pull/56087/](https://ci.nodejs.org/job/node-test-pull-request/64045/), [https://github.com/nodejs/node/pull/56225/](https://ci.nodejs.org/job/node-test-pull-request/64047/), [https://github.com/nodejs/node/pull/56275/](https://ci.nodejs.org/job/node-test-pull-request/64071/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62609/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18101/console), [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18086/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63993/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64071/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62609/console">Example</a></summary>

```
not ok 4275 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3380.84600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-file-shared-dependency</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63993/), [https://github.com/nodejs/node/pull/56208/](https://ci.nodejs.org/job/node-test-pull-request/64001/), [https://github.com/nodejs/node/pull/56112/](https://ci.nodejs.org/job/node-test-pull-request/64006/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64035/), [https://github.com/nodejs/node/pull/56162/](https://ci.nodejs.org/job/node-test-pull-request/64039/), [https://github.com/nodejs/node/pull/56255/](https://ci.nodejs.org/job/node-test-pull-request/64064/), [https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64070/), [https://github.com/nodejs/node/pull/56278/](https://ci.nodejs.org/job/node-test-pull-request/64076/), [https://github.com/nodejs/node/pull/56282/](https://ci.nodejs.org/job/node-test-pull-request/64077/), [https://github.com/nodejs/node/pull/56147/](https://ci.nodejs.org/job/node-test-pull-request/64079/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62619/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18137/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63993/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64079/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62619/console">Example</a></summary>

```
not ok 3950 parallel/test-watch-file-shared-dependency
  ---
  duration_ms: 120144.32900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ watch file with shared dependency
      ✔ should not remove shared dependencies when unfiltering an owner (13.248638ms)
    ✔ watch file with shared dependency (16.621273ms)
  ...

```
</details>

-------

| Reason | <code>parallel/test-abortsignal-drop-settled-signals</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/53900/](https://ci.nodejs.org/job/node-test-pull-request/63993/), [https://github.com/nodejs/node/pull/56222/](https://ci.nodejs.org/job/node-test-pull-request/63997/), [https://github.com/nodejs/node/pull/56057/](https://ci.nodejs.org/job/node-test-pull-request/64007/), [https://github.com/nodejs/node/pull/55915/](https://ci.nodejs.org/job/node-test-pull-request/64008/), [https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64010/), [https://github.com/nodejs/node/pull/56068/](https://ci.nodejs.org/job/node-test-pull-request/64012/), [https://github.com/nodejs/node/pull/56224/](https://ci.nodejs.org/job/node-test-pull-request/64015/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64023/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56210/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47156/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14987/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/47880/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/47880/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/56801/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56199/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/47878/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39771/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47876/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/31650/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/47145/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47859/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63993/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64023/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56210/console">Example</a></summary>

```
not ok 107 parallel/test-abortsignal-drop-settled-signals
  ---
  duration_ms: 1244.12200
  severity: fail
  exitcode: 1
  stack: |-
    ▶ when there is a long-lived signal
      ✔ drops settled dependant signals (204.388378ms)
      ✔ keeps all active dependant signals (166.05137ms)
    ✔ when there is a long-lived signal (374.422057ms)
    ✔ does not prevent source signal from being GCed if it is short-lived (171.42437ms)
    ✖ drops settled dependant signals when signal is composite (12.319813ms)
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
      
      2 !== 0
      
          at assert.<computed> [as strictEqual] (node:internal/test_runner/test:263:18)
          at Immediate._onImmediate (file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-abortsignal-drop-settled-signals.mjs:151:16)
          at process.processImmediate (node:internal/timers:511:21) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: 2,
        expected: 0...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56197/](https://ci.nodejs.org/job/node-test-pull-request/64009/), [https://github.com/nodejs/node/pull/56239/](https://ci.nodejs.org/job/node-test-pull-request/64031/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64032/), [https://github.com/nodejs/node/pull/56060/](https://ci.nodejs.org/job/node-test-pull-request/64033/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56212/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56196/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64033/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console">Example</a></summary>

```
not ok 847 parallel/test-file-write-stream4
  ---
  duration_ms: 1881.38400
  severity: fail
  exitcode: 1
  stack: |-
    node:events:491
          throw er; // Unhandled 'error' event
          ^
    
    Error: ENOSPC: no space left on device, write
    Emitted 'error' event on WriteStream instance at:
        at WriteStream.onerror (node:internal/streams/readable:1026:14)
        at WriteStream.emit (node:events:513:28)
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      errno: -28,
      code: 'ENOSPC',
      syscall: 'write'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-module-loading-globalpaths</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56068/](https://ci.nodejs.org/job/node-test-pull-request/64025/), [https://github.com/nodejs/node/pull/56239/](https://ci.nodejs.org/job/node-test-pull-request/64031/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64032/), [https://github.com/nodejs/node/pull/56060/](https://ci.nodejs.org/job/node-test-pull-request/64033/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64025/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64033/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console">Example</a></summary>

```
not ok 1942 parallel/test-module-loading-globalpaths
  ---
  duration_ms: 2077.91600
  severity: fail
  exitcode: 1
  stack: |-
    node:fs:3088
      binding.copyFile(
              ^
    
    Error: ENOSPC: no space left on device, copyfile '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/out/Release/node' -> '/Users/iojs/node-tmp/.tmp.1940/install/bin/node'
        at Object.copyFileSync (node:fs:3088:11)
        at Object.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-module-loading-globalpaths.js:32:6)
        at Module._compile (node:internal/modules/cjs/loader:1740:14)
        at Object..js (node:internal/modules/cjs/loader:1905:10)
        at Module.load (node:internal/modules/cjs/loader:1474:32)
        at Function._load (node:internal/modules/cjs/loader:1286:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
        at Function.executeUserEntry...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56224/](https://ci.nodejs.org/job/node-test-pull-request/64003/), [https://github.com/nodejs/node/pull/56201/](https://ci.nodejs.org/job/node-test-pull-request/64004/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64023/), [https://github.com/nodejs/node/pull/55964/](https://ci.nodejs.org/job/node-test-pull-request/64052/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/47919/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/58142/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56194/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47873/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64003/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64052/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/47919/console">Example</a></summary>

```
not ok 3332 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 120074.26000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-child-process-fork-exec-path</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56239/](https://ci.nodejs.org/job/node-test-pull-request/64031/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64032/), [https://github.com/nodejs/node/pull/56060/](https://ci.nodejs.org/job/node-test-pull-request/64033/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64031/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64033/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console">Example</a></summary>

```
not ok 204 parallel/test-child-process-fork-exec-path
  ---
  duration_ms: 3025.60900
  severity: fail
  exitcode: 1
  stack: |-
    node:fs:3088
      binding.copyFile(
              ^
    
    Error: ENOSPC: no space left on device, copyfile '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/out/Release/node' -> '/Users/iojs/node-tmp/.tmp.191/node-copy.exe'
        at Object.copyFileSync (node:fs:3088:11)
        at Object.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-child-process-fork-exec-path.js:50:4)
        at Module._compile (node:internal/modules/cjs/loader:1740:14)
        at Object..js (node:internal/modules/cjs/loader:1905:10)
        at Module.load (node:internal/modules/cjs/loader:1474:32)
        at Function._load (node:internal/modules/cjs/loader:1286:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
        at Function.executeUserEntryP...
```
</details>

-------

| Reason | <code>parallel/test-http-chunk-problem</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56222/](https://ci.nodejs.org/job/node-test-pull-request/63997/), [https://github.com/nodejs/node/pull/56087/](https://ci.nodejs.org/job/node-test-pull-request/64045/), [https://github.com/nodejs/node/pull/55964/](https://ci.nodejs.org/job/node-test-pull-request/64046/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47909/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47866/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63997/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64046/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47909/console">Example</a></summary>

```
not ok 1487 parallel/test-http-chunk-problem
  ---
  duration_ms: 120042.44200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56239/](https://ci.nodejs.org/job/node-test-pull-request/64031/), [https://github.com/nodejs/node/pull/56256/](https://ci.nodejs.org/job/node-test-pull-request/64059/), [https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64070/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56254/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/56239/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/47895/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64031/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64070/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56254/console">Example</a></summary>

```
not ok 4183 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360024.31100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-find-package-json</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64032/), [https://github.com/nodejs/node/pull/56060/](https://ci.nodejs.org/job/node-test-pull-request/64033/)) |
| Appeared | [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64032/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64033/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62558/console">Example</a></summary>

```
not ok 845 parallel/test-find-package-json
  ---
  duration_ms: 589.54400
  severity: fail
  exitcode: 1
  stack: |-
    ▶ findPackageJSON
      ✔ should throw when no arguments are provided (4.950601ms)
      ✔ should throw when parentLocation is invalid (2.34029ms)
      ✔ should accept a file URL (string), like from `import.meta.resolve()` (7.966507ms)
      ✔ should accept a file URL instance (1.62235ms)
      ✔ should be able to crawl up (CJS) (10.375735ms)
      ✔ should be able to crawl up (ESM) (9.834127ms)
      ✔ can require via package.json (7.705549ms)
      ✖ should be able to resolve both root and closest package.json (117.765527ms)
        Error: ENOSPC: no space left on device, write
            at Object.writeFileSync (node:fs:2428:20)
            at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-find-package-json.js:119:8)
            at Test.runInAsyncScope (node:async_hooks:211:14)
            at Test.run (node:internal/test_run...
```
</details>

-------

| Reason | <code>pummel/test-hash-seed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56087/](https://ci.nodejs.org/job/node-test-pull-request/64045/), [https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64070/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62152/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64045/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64070/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62152/console">Example</a></summary>

```
not ok 3962 pummel/test-hash-seed
  ---
  duration_ms: 68407.94500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/errors:983
      const err = new Error(message);
                  ^
    
    Error: Command failed: /home/iojs/build/workspace/node/out/Release/node --allow-natives-syntax /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js
    /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163
      throw new Error('no candidates remaining');
      ^
    
    Error: no candidates remaining
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163:9)
        at Module._compile (node:internal/modules/cjs/loader:1740:14)
        at Object..js (node:internal/modules/cjs/loader:1905:10)
        at Module.load (node:internal/modules/cjs/loader:1474:32)
        at Function._load (node:internal/modules/cjs/loader:1286:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/mod...
```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56255/](https://ci.nodejs.org/job/node-test-pull-request/64060/), [https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64070/)) |
| Appeared | [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58185/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58171/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64060/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64070/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58185/console">Example</a></summary>

```
not ok 4371 sequential/test-worker-prof
  ---
  duration_ms: 1929.95100
  severity: fail
  exitcode: 1
  stack: |-
    [process 19232]: --- stderr ---
    
    [process 19232]: --- stdout ---
    files found in working directory before worker starts [ 'isolate-0x819d000-19232-v8.log' ]
    parent prof file: isolate-0x819d000-19232-v8.log
    parent posted 8404 messages
    files found in working directory before worker exits [ 'isolate-0x819d000-19232-v8.log', 'isolate-0x84fb000-19232-v8.log' ]
    worker prof file: isolate-0x84fb000-19232-v8.log
    
    [process 19232]: status = null, signal = SIGPROF
    /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGPROF, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/test/sequential/test-worker-prof.js:53:22)
  ...
```
</details>

-------


### Jenkins Failure


### Git Failure


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56224/](https://ci.nodejs.org/job/node-test-pull-request/64003/), [https://github.com/nodejs/node/pull/56201/](https://ci.nodejs.org/job/node-test-pull-request/64004/), [https://github.com/nodejs/node/pull/56226/](https://ci.nodejs.org/job/node-test-pull-request/64005/), [https://github.com/nodejs/node/pull/56250/](https://ci.nodejs.org/job/node-test-pull-request/64043/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62572/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18097/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47874/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47873/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64003/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64043/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62572/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56218/](https://ci.nodejs.org/job/node-test-pull-request/64034/), [https://github.com/nodejs/node/pull/55964/](https://ci.nodejs.org/job/node-test-pull-request/64052/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15021/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/15021/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/58147/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64034/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64052/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15021/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins12715402761339760045.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------

| Reason | <code>fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56228/](https://ci.nodejs.org/job/node-test-pull-request/64017/), [https://github.com/nodejs/node/pull/55620/](https://ci.nodejs.org/job/node-test-pull-request/64023/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14994/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14988/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64017/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64023/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14994/console">Example</a></summary>

```
fatal: '/home/iojs/.ccache/node.shared.reference' does not appear to be a git repository
fatal: Could not read from remote repository.
```
</details>

-------

