Failures in [node-test-pull-request/64110](https://ci.nodejs.org/job/node-test-pull-request/64110/) to [node-test-pull-request/64199](https://ci.nodejs.org/job/node-test-pull-request/64199/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-12-25.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-12-25 00:10 | 0       | 12      | 16       | 15      | 57      | 14.12%     |


### Jenkins Failure


### Git Failure


### Build Failure

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56325/](https://ci.nodejs.org/job/node-test-pull-request/64149/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64167/)) |
| Appeared | [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15131/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58280/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64149/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64167/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15131/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[PostBuildScript] - [INFO] Executing post build scripts.
[node-test-binary-armv7l] $ /bin/bash -ex /tmp/jenkins13760763845883183201.sh
+ '[' -d .git ']'
+ git clean -fdx
Removing out/
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56329/](https://ci.nodejs.org/job/node-test-pull-request/64141/), [https://github.com/nodejs/node/pull/56344/](https://ci.nodejs.org/job/node-test-pull-request/64191/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48069/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/58096/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64141/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64191/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48069/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/56211/](https://ci.nodejs.org/job/node-test-pull-request/64146/), [https://github.com/nodejs/node/pull/56332/](https://ci.nodejs.org/job/node-test-pull-request/64151/), [https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64166/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64168/), [https://github.com/nodejs/node/pull/50482/](https://ci.nodejs.org/job/node-test-pull-request/64180/), [https://github.com/nodejs/node/pull/56302/](https://ci.nodejs.org/job/node-test-pull-request/64184/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64190/), [https://github.com/nodejs/node/pull/56240/](https://ci.nodejs.org/job/node-test-pull-request/64198/), [https://github.com/nodejs/node/pull/56352/](https://ci.nodejs.org/job/node-test-pull-request/64199/)) |
| Appeared | [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18265/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62738/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62718/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64146/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64199/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18265/console">Example</a></summary>

```
not ok 4278 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3188.76500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56310/](https://ci.nodejs.org/job/node-test-pull-request/64113/), [https://github.com/nodejs/node/pull/56298/](https://ci.nodejs.org/job/node-test-pull-request/64126/), [https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64132/), [https://github.com/nodejs/node/pull/56325/](https://ci.nodejs.org/job/node-test-pull-request/64149/), [https://github.com/nodejs/node/pull/56341/](https://ci.nodejs.org/job/node-test-pull-request/64187/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64190/)) |
| Appeared | [test-mnx-smartos23-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58322/console), [test-mnx-smartos22-x64-2](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58316/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/58260/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58254/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64113/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64190/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/58322/console">Example</a></summary>

```
not ok 4373 sequential/test-worker-prof
  ---
  duration_ms: 1929.78700
  severity: fail
  exitcode: 1
  stack: |-
    [process 72167]: --- stderr ---
    
    [process 72167]: --- stdout ---
    files found in working directory before worker starts [ 'isolate-0x81a6000-72167-v8.log' ]
    parent prof file: isolate-0x81a6000-72167-v8.log
    parent posted 9777 messages
    files found in working directory before worker exits [ 'isolate-0x81a6000-72167-v8.log', 'isolate-0x8504000-72167-v8.log' ]
    worker prof file: isolate-0x8504000-72167-v8.log
    
    [process 72167]: status = null, signal = SIGPROF
    /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGPROF, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos23-x64/test/sequential/test-worker-prof.js:53:22)
  ...
```
</details>

-------

| Reason | <code>parallel/test-watch-file-shared-dependency</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64110/), [https://github.com/nodejs/node/pull/56299/](https://ci.nodejs.org/job/node-test-pull-request/64124/), [https://github.com/nodejs/node/pull/56332/](https://ci.nodejs.org/job/node-test-pull-request/64151/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64167/), [https://github.com/nodejs/node/pull/56349/](https://ci.nodejs.org/job/node-test-pull-request/64188/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62743/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62724/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64110/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64188/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/62743/console">Example</a></summary>

```
not ok 3951 parallel/test-watch-file-shared-dependency
  ---
  duration_ms: 120073.10800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ watch file with shared dependency
      ✔ should not remove shared dependencies when unfiltering an owner (16.197949ms)
    ✔ watch file with shared dependency (19.853204ms)
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56303/](https://ci.nodejs.org/job/node-test-pull-request/64130/), [https://github.com/nodejs/node/pull/56325/](https://ci.nodejs.org/job/node-test-pull-request/64136/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64177/), [https://github.com/nodejs/node/pull/56344/](https://ci.nodejs.org/job/node-test-pull-request/64185/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48061/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/56358/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/18191/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64130/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64185/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48061/console">Example</a></summary>

```
not ok 1487 parallel/test-file-write-stream4
  ---
  duration_ms: 120045.90000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>es-module/test-wasm-web-api</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56298/](https://ci.nodejs.org/job/node-test-pull-request/64125/), [https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64148/), [https://github.com/nodejs/node/pull/56231/](https://ci.nodejs.org/job/node-test-pull-request/64165/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48044/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48027/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47997/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64125/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64165/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48044/console">Example</a></summary>

```
not ok 3828 es-module/test-wasm-web-api
  ---
  duration_ms: 612.95300
  severity: fail
  exitcode: 1
  stack: |-
    (node:3510768) Warning: Closing file descriptor 27 on garbage collection
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:3510768) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
    node:internal/wasm_web_api:56
        streamState.finish();
                    ^
    
    CompileError: WebAssembly.compileStreaming(): expected 4 bytes, fell off end @+0
        at node:internal/wasm_web_api:56:17
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-abortsignal-drop-settled-signals</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56329/](https://ci.nodejs.org/job/node-test-pull-request/64143/), [https://github.com/nodejs/node/pull/56334/](https://ci.nodejs.org/job/node-test-pull-request/64150/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39911/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64143/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64150/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39911/console">Example</a></summary>

```
not ok 400 parallel/test-abortsignal-drop-settled-signals
  ---
  duration_ms: 2016.13200
  severity: fail
  exitcode: 1
  stack: |-
    ▶ when there is a long-lived signal
      ✔ drops settled dependant signals (396.375133ms)
      ✔ keeps all active dependant signals (295.167313ms)
    ✔ when there is a long-lived signal (695.403171ms)
    ✔ does not prevent source signal from being GCed if it is short-lived (289.882166ms)
    ✖ drops settled dependant signals when signal is composite (13.987205ms)
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
      
      2 !== 0
      
          at assert.<computed> [as strictEqual] (node:internal/test_runner/test:263:18)
          at Immediate._onImmediate (file:///home/iojs/build/workspace/node/test/parallel/test-abortsignal-drop-settled-signals.mjs:151:18)
          at process.processImmediate (node:internal/timers:511:21) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: 2,
        expected: 0,
        oper...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56285/](https://ci.nodejs.org/job/node-test-pull-request/64189/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64197/)) |
| Appeared | [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62273/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/56368/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64189/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64197/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/62273/console">Example</a></summary>

```
not ok 3366 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 120047.41100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64132/), [https://github.com/nodejs/node/pull/55481/](https://ci.nodejs.org/job/node-test-pull-request/64142/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48013/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48000/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64132/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64142/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48013/console">Example</a></summary>

```
not ok 3957 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 120048.19600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-hash-seed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55844/](https://ci.nodejs.org/job/node-test-pull-request/64132/), [https://github.com/nodejs/node/pull/56344/](https://ci.nodejs.org/job/node-test-pull-request/64172/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62254/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64132/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64172/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/62254/console">Example</a></summary>

```
not ok 3965 pummel/test-hash-seed
  ---
  duration_ms: 68209.17300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/errors:983
      const err = new Error(message);
                  ^
    
    Error: Command failed: /home/iojs/build/workspace/node/out/Release/node --allow-natives-syntax /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js
    /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163
      throw new Error('no candidates remaining');
      ^
    
    Error: no candidates remaining
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163:9)
        at Module._compile (node:internal/modules/cjs/loader:1740:14)
        at Object..js (node:internal/modules/cjs/loader:1905:10)
        at Module.load (node:internal/modules/cjs/loader:1474:32)
        at Function._load (node:internal/modules/cjs/loader:1286:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/mod...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56237/](https://ci.nodejs.org/job/node-test-pull-request/64148/), [https://github.com/nodejs/node/pull/56335/](https://ci.nodejs.org/job/node-test-pull-request/64177/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48057/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48027/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/64148/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/64177/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48057/console">Example</a></summary>

```
not ok 4375 sequential/test-tls-session-timeout
  ---
  duration_ms: 135.53900
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:126
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:146:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:130:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

