Failures in [node-test-pull-request/66109](https://ci.nodejs.org/job/node-test-pull-request/66109/) to [node-test-pull-request/66207](https://ci.nodejs.org/job/node-test-pull-request/66207/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-04-12.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-04-12 00:10 | 0       | 0       | 23       | 3       | 74      | 0.00%      |


### JSTest Failure

| Reason | <code>pummel/test-buffer-large-size</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 24 ([https://github.com/nodejs/node/pull/57589/](https://ci.nodejs.org/job/node-test-pull-request/66113/), [https://github.com/nodejs/node/pull/57664/](https://ci.nodejs.org/job/node-test-pull-request/66116/), [https://github.com/nodejs/node/pull/57770/](https://ci.nodejs.org/job/node-test-pull-request/66124/), [https://github.com/nodejs/node/pull/57732/](https://ci.nodejs.org/job/node-test-pull-request/66128/), [https://github.com/nodejs/node/pull/57792/](https://ci.nodejs.org/job/node-test-pull-request/66132/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66140/), [https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66146/), [https://github.com/nodejs/node/pull/56600/](https://ci.nodejs.org/job/node-test-pull-request/66147/), [https://github.com/nodejs/node/pull/57787/](https://ci.nodejs.org/job/node-test-pull-request/66149/), [https://github.com/nodejs/node/pull/57672/](https://ci.nodejs.org/job/node-test-pull-request/66153/), [https://github.com/nodejs/node/pull/57791/](https://ci.nodejs.org/job/node-test-pull-request/66157/), [https://github.com/nodejs/node/pull/57591/](https://ci.nodejs.org/job/node-test-pull-request/66164/), [https://github.com/nodejs/node/pull/57683/](https://ci.nodejs.org/job/node-test-pull-request/66166/), [https://github.com/nodejs/node/pull/57806/](https://ci.nodejs.org/job/node-test-pull-request/66171/), [https://github.com/nodejs/node/pull/57738/](https://ci.nodejs.org/job/node-test-pull-request/66176/), [https://github.com/nodejs/node/pull/57798/](https://ci.nodejs.org/job/node-test-pull-request/66178/), [https://github.com/nodejs/node/pull/57801/](https://ci.nodejs.org/job/node-test-pull-request/66179/), [https://github.com/nodejs/node/pull/57811/](https://ci.nodejs.org/job/node-test-pull-request/66182/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66184/), [https://github.com/nodejs/node/pull/57803/](https://ci.nodejs.org/job/node-test-pull-request/66185/), [https://github.com/nodejs/node/pull/57646/](https://ci.nodejs.org/job/node-test-pull-request/66188/), [https://github.com/nodejs/node/pull/57642/](https://ci.nodejs.org/job/node-test-pull-request/66189/), [https://github.com/nodejs/node/pull/57576/](https://ci.nodejs.org/job/node-test-pull-request/66191/), [https://github.com/nodejs/node/pull/57609/](https://ci.nodejs.org/job/node-test-pull-request/66198/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50033/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50022/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/50022/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/50019/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/50021/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50013/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/50012/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50004/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/49997/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/49997/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/49993/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/64014/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49968/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/49959/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/49952/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/49949/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66113/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66198/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50033/console">Example</a></summary>

```
not ok 4035 pummel/test-buffer-large-size
  ---
  duration_ms: 720025.39000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:2883004) [DEP0030] DeprecationWarning: SlowBuffer() is deprecated. Please use Buffer.allocUnsafeSlow()
    (Use `node --trace-deprecation ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-repl-custom-eval</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/57683/](https://ci.nodejs.org/job/node-test-pull-request/66118/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66127/), [https://github.com/nodejs/node/pull/57787/](https://ci.nodejs.org/job/node-test-pull-request/66129/), [https://github.com/nodejs/node/pull/56600/](https://ci.nodejs.org/job/node-test-pull-request/66131/), [https://github.com/nodejs/node/pull/57789/](https://ci.nodejs.org/job/node-test-pull-request/66133/), [https://github.com/nodejs/node/pull/57732/](https://ci.nodejs.org/job/node-test-pull-request/66138/), [https://github.com/nodejs/node/pull/57794/](https://ci.nodejs.org/job/node-test-pull-request/66139/), [https://github.com/nodejs/node/pull/57792/](https://ci.nodejs.org/job/node-test-pull-request/66141/), [https://github.com/nodejs/node/pull/57770/](https://ci.nodejs.org/job/node-test-pull-request/66143/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66144/), [https://github.com/nodejs/node/pull/57791/](https://ci.nodejs.org/job/node-test-pull-request/66145/), [https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66146/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49968/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49967/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49966/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49964/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49963/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49961/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49960/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49937/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49936/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66118/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66146/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49968/console">Example</a></summary>

```
not ok 2422 parallel/test-repl-custom-eval
  ---
  duration_ms: 212.04800
  severity: fail
  exitcode: 1
  stack: |-
    > > > > Test failure: 'does show previews if `preview` is set to `true`'
    Location: test/parallel/test-repl-custom-eval.js:121:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /'Hello custom' \+ ' eval World!'\n\/\/ 'Hello custom eval World!'/. Input:
    
    "'Hello custom' + ' eval World!'"
    
        at TestContext.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-repl-custom-eval.js:130:12)
        at Test.runInAsyncScope (node:async_hooks:214:14)
        at Test.run (node:internal/test_runner/test:1056:25)
        at Test.start (node:internal/test_runner/test:953:17)
        at node:internal/test_runner/test:1452:71
        at node:internal/per_context/primordials:483:82
        at new Promise (<anonymous>)
        at new SafePromise (node:internal/per_context/primordials:451:29)
        at node:inter...
```
</details>

-------

| Reason | <code>parallel/test-runner-plan</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/57794/](https://ci.nodejs.org/job/node-test-pull-request/66139/), [https://github.com/nodejs/node/pull/57787/](https://ci.nodejs.org/job/node-test-pull-request/66149/), [https://github.com/nodejs/node/pull/57672/](https://ci.nodejs.org/job/node-test-pull-request/66158/), [https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66165/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66177/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66200/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/33581/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66139/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66200/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/33581/console">Example</a></summary>

```
not ok 713 parallel/test-runner-plan
  ---
  duration_ms: 2169.01200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'throws if options is not an object'
    Location: test\parallel\test-runner-plan.mjs:9:3
    AssertionError [ERR_ASSERTION]: Missing expected exception.
        at assert.<computed> [as throws] (node:internal/test_runner/test:254:18)
        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-plan.mjs:10:14)
        at Test.runInAsyncScope (node:async_hooks:214:14)
        at Test.run (node:internal/test_runner/test:979:25)
        at Test.start (node:internal/test_runner/test:877:17)
        at node:internal/test_runner/test:1356:71
        at node:internal/per_context/primordials:483:82
        at new Promise (<anonymous>)
        at new SafePromise (node:internal/per_context/primordials:451:29)
        at node:internal/per_context/primordials:483:9 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      ...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56600/](https://ci.nodejs.org/job/node-test-pull-request/66147/), [https://github.com/nodejs/node/pull/57791/](https://ci.nodejs.org/job/node-test-pull-request/66148/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66162/), [https://github.com/nodejs/node/pull/57806/](https://ci.nodejs.org/job/node-test-pull-request/66171/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66177/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/50002/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/58002/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57998/console), [vm-5zzvx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/64491/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/49962/console), [vm-bb66d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/64487/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66147/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66177/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/50002/console">Example</a></summary>

```
not ok 1510 parallel/test-file-write-stream4
  ---
  duration_ms: 120101.62300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-crypto-authenticated</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57591/](https://ci.nodejs.org/job/node-test-pull-request/66164/), [https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66165/), [https://github.com/nodejs/node/pull/57806/](https://ci.nodejs.org/job/node-test-pull-request/66175/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50000/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/33548/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66164/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66175/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50000/console">Example</a></summary>

```
not ok 1299 parallel/test-crypto-authenticated
  ---
  duration_ms: 120105.45100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-chunk-problem</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57732/](https://ci.nodejs.org/job/node-test-pull-request/66123/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66134/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49956/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49941/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66123/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66134/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49956/console">Example</a></summary>

```
not ok 1500 parallel/test-http-chunk-problem
  ---
  duration_ms: 120032.84200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57775/](https://ci.nodejs.org/job/node-test-pull-request/66196/), [https://github.com/nodejs/node/pull/57835/](https://ci.nodejs.org/job/node-test-pull-request/66201/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50036/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/50031/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66196/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66201/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50036/console">Example</a></summary>

```
not ok 4044 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 120060.38700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-zlib-convenience-methods</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57591/](https://ci.nodejs.org/job/node-test-pull-request/66114/), [https://github.com/nodejs/node/pull/56600/](https://ci.nodejs.org/job/node-test-pull-request/66122/)) |
| Appeared | [vm-q6m8r](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64475/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49933/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66114/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66122/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64475/console">Example</a></summary>

```
not ok 4049 parallel/test-zlib-convenience-methods
  ---
  duration_ms: 120010.98100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66125/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66177/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/50002/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66125/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66177/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/50002/console">Example</a></summary>

```
not ok 4388 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7329.13400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------


### Jenkins Failure


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57646/](https://ci.nodejs.org/job/node-test-pull-request/66188/), [https://github.com/nodejs/node/pull/57578/](https://ci.nodejs.org/job/node-test-pull-request/66190/), [https://github.com/nodejs/node/pull/57576/](https://ci.nodejs.org/job/node-test-pull-request/66191/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/64045/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66188/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66191/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/64045/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Error: list index out of range</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/57794/](https://ci.nodejs.org/job/node-test-pull-request/66139/), [https://github.com/nodejs/node/pull/57787/](https://ci.nodejs.org/job/node-test-pull-request/66149/), [https://github.com/nodejs/node/pull/57672/](https://ci.nodejs.org/job/node-test-pull-request/66158/), [https://github.com/nodejs/node/pull/57667/](https://ci.nodejs.org/job/node-test-pull-request/66165/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66177/), [https://github.com/nodejs/node/pull/57586/](https://ci.nodejs.org/job/node-test-pull-request/66200/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022_clang/33184/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022_clang/33184/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022_clang/33184/console), [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022_clang/33184/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66139/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66200/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022_clang/33184/console">Example</a></summary>

```
Error: list index out of range

> if errorlevel 1 exit /b 

> if errorlevel 1 exit /b
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56600/](https://ci.nodejs.org/job/node-test-pull-request/66131/), [https://github.com/nodejs/node/pull/57792/](https://ci.nodejs.org/job/node-test-pull-request/66141/), [https://github.com/nodejs/node/pull/57438/](https://ci.nodejs.org/job/node-test-pull-request/66174/), [https://github.com/nodejs/node/pull/57811/](https://ci.nodejs.org/job/node-test-pull-request/66194/)) |
| Appeared | [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/48933/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49999/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49963/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66131/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66194/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/48933/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

