Failures in [node-test-pull-request/66563](https://ci.nodejs.org/job/node-test-pull-request/66563/) to [node-test-pull-request/66653](https://ci.nodejs.org/job/node-test-pull-request/66653/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-05-07.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-05-07 00:11 | 9       | 10      | 14       | 10      | 57      | 12.35%     |


### Jenkins Failure

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66598/), [https://github.com/nodejs/node/pull/58171/](https://ci.nodejs.org/job/node-test-pull-request/66600/), [https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66618/), [https://github.com/nodejs/node/pull/58103/](https://ci.nodejs.org/job/node-test-pull-request/66621/), [https://github.com/nodejs/node/pull/58122/](https://ci.nodejs.org/job/node-test-pull-request/66622/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66623/), [https://github.com/nodejs/node/pull/58181/](https://ci.nodejs.org/job/node-test-pull-request/66638/), [https://github.com/nodejs/node/pull/58163/](https://ci.nodejs.org/job/node-test-pull-request/66639/), [https://github.com/nodejs/node/pull/58182/](https://ci.nodejs.org/job/node-test-pull-request/66640/), [https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66643/), [https://github.com/nodejs/node/pull/58190/](https://ci.nodejs.org/job/node-test-pull-request/66645/), [https://github.com/nodejs/node/pull/58144/](https://ci.nodejs.org/job/node-test-pull-request/66646/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50502/console), [vm-g7z6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64943/console), [vm-d54f5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64937/console), [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64918/console), [vm-zgnbb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64917/console), [vm-lkh4k](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64916/console), [vm-4dn6g](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64895/console), [vm-fd526](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64894/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66598/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66646/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50502/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/58122/](https://ci.nodejs.org/job/node-test-pull-request/66622/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66625/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66627/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66631/), [https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66634/), [https://github.com/nodejs/node/pull/58184/](https://ci.nodejs.org/job/node-test-pull-request/66635/), [https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66647/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34057/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34050/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34040/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34040/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66565/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66647/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34057/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58124/](https://ci.nodejs.org/job/node-test-pull-request/66577/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66630/), [https://github.com/nodejs/node/pull/58190/](https://ci.nodejs.org/job/node-test-pull-request/66653/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/66653/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66577/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66653/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/66653/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------


### JSTest Failure

| Reason | <code>pummel/test-heapdump-zlib</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/58150/](https://ci.nodejs.org/job/node-test-pull-request/66578/), [https://github.com/nodejs/node/pull/57924/](https://ci.nodejs.org/job/node-test-pull-request/66580/), [https://github.com/nodejs/node/pull/58157/](https://ci.nodejs.org/job/node-test-pull-request/66588/), [https://github.com/nodejs/node/pull/58143/](https://ci.nodejs.org/job/node-test-pull-request/66626/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66627/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/34040/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34039/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34002/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/50440/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/50440/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/33998/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/33998/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/50437/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50437/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/33989/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/33989/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/33980/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50418/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66565/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66627/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/34040/console">Example</a></summary>

```
not ok 1019 pummel/test-heapdump-zlib
  ---
  duration_ms: 720222.55000
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66564/), [https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66570/), [https://github.com/nodejs/node/pull/58150/](https://ci.nodejs.org/job/node-test-pull-request/66578/), [https://github.com/nodejs/node/pull/58151/](https://ci.nodejs.org/job/node-test-pull-request/66647/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/34062/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66564/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66647/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/34062/console">Example</a></summary>

```
not ok 104 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 293.01900
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:377
          throw err;
          ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
      Comparison {
    +   name: 'RangeError'
    -   code: 'ERR_STRING_TOO_LONG',
    -   name: 'Error'
      }
        at Object.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-rangeerror.js:21:8)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSE...
```
</details>

-------

| Reason | <code>pummel/test-heapdump-worker</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/57931/](https://ci.nodejs.org/job/node-test-pull-request/66564/), [https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66573/), [https://github.com/nodejs/node/pull/57924/](https://ci.nodejs.org/job/node-test-pull-request/66580/), [https://github.com/nodejs/node/pull/58152/](https://ci.nodejs.org/job/node-test-pull-request/66582/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/50439/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/50437/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/50425/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/50423/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/50423/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50423/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66564/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66582/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/50439/console">Example</a></summary>

```
not ok 4084 pummel/test-heapdump-worker
  ---
  duration_ms: 720051.66500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-client-socket-destroy</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66629/), [https://github.com/nodejs/node/pull/56534/](https://ci.nodejs.org/job/node-test-pull-request/66631/)) |
| Appeared | [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64927/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66624/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66631/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64927/console">Example</a></summary>

```
not ok 1552 parallel/test-http2-client-socket-destroy
  ---
  duration_ms: 202.50200
  severity: fail
  exitcode: 1
  stack: |-
    node:events:485
          throw er; // Unhandled 'error' event
          ^
    
    Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
    Emitted 'error' event on ServerHttp2Stream instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      errno: -54,
      code: 'ECONNRESET',
      syscall: 'read'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57643/](https://ci.nodejs.org/job/node-test-pull-request/66606/), [https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58183/](https://ci.nodejs.org/job/node-test-pull-request/66625/)) |
| Appeared | [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64921/console), [vm-5cpq7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66606/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66625/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64921/console">Example</a></summary>

```
not ok 2533 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120074.07300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-heapdump-shadow-realm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/57924/](https://ci.nodejs.org/job/node-test-pull-request/66572/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66573/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50425/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50422/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66565/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66573/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50425/console">Example</a></summary>

```
not ok 4080 pummel/test-heapdump-shadow-realm
  ---
  duration_ms: 720041.72000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58173/](https://ci.nodejs.org/job/node-test-pull-request/66624/), [https://github.com/nodejs/node/pull/58124/](https://ci.nodejs.org/job/node-test-pull-request/66641/)) |
| Appeared | [vm-g7z6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64939/console), [vm-nm7dc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64920/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66624/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66641/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/64939/console">Example</a></summary>

```
not ok 2628 parallel/test-runner-run-watch
  ---
  duration_ms: 23057.79000
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 1, actual 2.
        at Module.mustCall (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/index.js:393:10)
        at TestContext.<anonymous> (file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:324:37)
        at Test.runInAsyncScope (node:async_hooks:214:14)
        at Test.run (node:internal/test_runner/test:1062:25)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:752:7)
  ...

```
</details>

-------

| Reason | <code>pummel/test-heapdump-tls</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/66565/), [https://github.com/nodejs/node/pull/58141/](https://ci.nodejs.org/job/node-test-pull-request/66570/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/50422/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50418/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/66565/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/66570/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/50422/console">Example</a></summary>

```
not ok 4081 pummel/test-heapdump-tls
  ---
  duration_ms: 720100.59800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

